### ISSUE TITLE
Refactoring - configure transaction management. Use @Transactional annotation

### ISSUE THREAD

**Issue by gancherya** [denis180889/Warehouse#10]
1.
Use @Transactional annotation instead of custom code in each dao method
Helpful resources:
- http://stackoverflow.com/questions/13066017/transactional-in-springhibernate
- http://www.byteslounge.com/tutorials/spring-with-hibernate-persistence-and-transactions-example

2.
 Adjust code marked with TODO.

**Comment by denis180889** [comment]
Task has been finished. Please review PR
