### ISSUE TITLE
Bean validation

### ISSUE THREAD

**Issue by gancherya** [denis180889/Warehouse#20]
1. Validate latitude and longitude to be in range  -90 and +90 for latitude, -180 and 180 for longitude. In case incorrect data is provided return http status code 400 and json data with error code, e.g. 
   {
   "ERROR_CODE" : "INVALID_LATITUDE"
   }
2. Validate warehouse and goods name to contain only latin alphabetical symbols. ERROR_CODE - INVALID_WAREHOUSE_NAME and INVALID_GOODS_NAME
3. Validate name and description of warehouse and goods  to not be the same (case insensitive, ignore whitespaces), i.e. following values should fail validation: name - "my Warehouse", description - "Mywarehouse". ERROR_CODE - INVALID_DESCRIPTION
4. Add integration tests to cover following scenarios:
   *\* longitude/latitude value is in correct range/not in correct range
   *\* warehouse name contains only alphabetical symbols/also contains numbers
   *\* goods name and description are the same/not the same
   In tests for longitude/latitude use random generator to generate values.

**Comment by denis180889** [comment]
1) return Response.ok(new SingleResult(warehouseId)).build(); 
2) Move validation logic from service to resource

**Comment by gancherya** [comment]
Some issues are present, but they will be fixed in separate tickets:
- https://github.com/denis180889/Warehouse/issues/25
