### ISSUE TITLE
Create project module "warehouse-database", add sql script for warehouse table

### ISSUE THREAD

**Issue by gancherya** [denis180889/Warehouse#4]
Create child module "warehouse-database" (packaging jar).
Create sql sript for warehouse table creation, add it to "warehouse-database" module (src/main/resources/migration) Table should be able to contain data coming in /warehouse POST call (s Rest API page)

Script naming convention - "V" + number + "__" + name, e.g. V1__create_warehouse_table

**Comment by denis180889** [comment]
Task has been done in database branch
