### ISSUE TITLE
spring_hibernate

### ISSUE THREAD

**Issue by denis180889** [denis180889/Warehouse#7]
Вопрос технологий и архитектуры.
Технологии:
Подключаем spring, подключаем Hibernate
http://www.journaldev.com/3524/spring-hibernate-integration-example-tutorial-spring-4-hibernate-3-and-hibernate-4
http://www.mkyong.com/spring/maven-spring-hibernate-mysql-example/
http://www.tutorialspoint.com/hibernate/

Архитектура:
Многоуровневая:
уровень 1 - в нашем случае ресурс (в других случаях контроллер)
уровень 2 - сервис
уровень 3- DAO (data access object)
уровень 4- model
Каждый верхний уровень может использовать объекты нижнего уровня, но не наоборот. Также верхний уровень может использовать только соседний нижний уровень, но не через один или два.
В нашем случае:
уровень 1 - WarehouseResource
уровень 2 - WarehouseService (пока просто вызывает методы WarehouseDao. В дальнейшем будет усложняться)
уровень 3 - WarehouseDao (предоставляет CRUD методы по работе с Warehouse)
уровень 4 - Warehouse (POJO (plain java object) - маппится через аннотации на таблицу)

**Comment by gancherya** [comment]
Closing issue. Everything related to spring and hibernate configuration will be done in separate small tickets
